from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("/data/fkj2023/pretrained_model/chatglm2-6b", trust_remote_code=True,local_files_only=True)
# model = AutoModel.from_pretrained("/data/fkj2023/pretrained_model/chatglm2-6b", trust_remote_code=True,local_files_only=True).half().cuda()
model = AutoModel.from_pretrained("/data/fkj2023/pretrained_model/chatglm2-6b", trust_remote_code=True,local_files_only=True).quantize(4).cuda()

model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)
